name: dbt CI/CD

on:
  push:
    branches:
      - master  # Ensure this is the primary branch you want to trigger the workflow
  pull_request:
    branches:
      - master

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your repository code

      - name: Set up Python
        uses: actions/setup-python@v2  # Setting up Python environment
        with:
          python-version: '3.8'  # Change to your preferred Python version if necessary

      - name: Install dependencies
        run: |
          pip install dbt-athena  # Install dbt dependency for Athena

      - name: Run dbt commands
        env:
          
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Credentials for AWS
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          dbt debug  
          dbt run    
          dbt test   
